### ISSUE TITLE
Ads being displayed only emulator

### ISSUE THREAD

**Issue by arvind1705** [deadcoder0904/expo-google-admob#3]
Ads are not being displayed on actual device. I even removed test device line.
Any known causes for this?

**Comment by henriquegranatto** [comment]
I have the same problem.

I generated an apk exactly the same as the example, I just changed the keys to my admob account.

In the Expo app it works however when I install the apk on my phone the ads are not displayed.

I'm using the latest version of Expo and my smartphone is an Android 6+

**Comment by deadcoder0904** [comment]
I missed this notification too (Idk how) 😂

Literally no idea. I'll try to update the code to support Expo SDK 32.

I think this issue must be submitted to https://github.com/sbugert/react-native-admob if it has this issue.

But it did work for my application when I tried over a year ago :)

Also make sure to check its docs & related issues too.

**Comment by deadcoder0904** [comment]
I updated it to support SDK v32 & now if you scan the QR code on a phone it works too :)
