### ISSUE TITLE
When you install the app the ads are not displayed.

### ISSUE THREAD

**Issue by henriquegranatto** [deadcoder0904/expo-google-admob#4]
I generated an apk exactly the same as the example, I just changed the keys to my admob account.

In the Expo app it works however when I install the apk on my phone the ads are not displayed.

I'm using the latest version of Expo and my smartphone is an Android 6+

**Comment by deadcoder0904** [comment]
Whoops sorry, I didn't receive any notification about this issue.

I think the ads should be displayed correctly. The problem might be the code isn't updated for a while to support Expo SDK 32 (which is latest as of now).

I'll try to update the code ASAP. In theory, it should work the same :)
